import { Prisma } from "@/generated/prisma/client"

const workPermitSelect = {
  id: true,
  status: true,
  isUrgent: true,
  requiresLockout: true,
  aplicantPt: true,
  mutuality: true,
  otherMutuality: true,
  exactPlace: true,
  workWillBe: true,
  workWillBeOther: true,
  tools: true,
  otherTools: true,
  preChecks: true,
  otherPreChecks: true,
  activityDetails: true,
  riskIdentification: true,
  otherRisk: true,
  preventiveControlMeasures: true,
  otherPreventiveControlMeasures: true,
  generateWaste: true,
  wasteType: true,
  wasteDisposalLocation: true,
  otherWasteDisposalLocation: true,
  whoDeliversWorkAreaOp: true,
  workerExecutor: true,
  workCompleted: true,
  cleanAndTidyWorkArea: true,
  additionalObservations: true,
  observations: true,
  acceptTerms: true,
  startDate: true,
  endDate: true,
  initialAreaMeasurement: true,
  approvalDate: true,
  approvalById: true,
  approvalBy: { select: { name: true } },
  approvalNotes: true,
  closingDate: true,
  closingById: true,
  closingBy: { select: { name: true } },
  preventionOfficerId: true,
  preventionOfficerUser: { select: { name: true } },
  otNumberId: true,
  otNumber: { select: { otNumber: true } },
  userId: true,
  user: { select: { name: true } },
  companyId: true,
  company: { select: { name: true } },
  _count: { select: { participants: true } },
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.WorkPermitSelect

export type WorkPermitRow = Prisma.WorkPermitGetPayload<{
  select: typeof workPermitSelect
}>

export { workPermitSelect }

export function flattenWorkPermit(row: WorkPermitRow) {
  return {
    id: row.id,
    status: row.status,
    isUrgent: row.isUrgent,
    requiresLockout: row.requiresLockout,
    aplicantPt: row.aplicantPt,
    mutuality: row.mutuality,
    otherMutuality: row.otherMutuality,
    exactPlace: row.exactPlace,
    workWillBe: row.workWillBe,
    workWillBeOther: row.workWillBeOther,
    tools: JSON.stringify(row.tools),
    otherTools: row.otherTools,
    preChecks: JSON.stringify(row.preChecks),
    otherPreChecks: row.otherPreChecks,
    activityDetails: JSON.stringify(row.activityDetails),
    riskIdentification: JSON.stringify(row.riskIdentification),
    otherRisk: row.otherRisk,
    preventiveControlMeasures: JSON.stringify(row.preventiveControlMeasures),
    otherPreventiveControlMeasures: row.otherPreventiveControlMeasures,
    generateWaste: row.generateWaste,
    wasteType: row.wasteType,
    wasteDisposalLocation: row.wasteDisposalLocation,
    otherWasteDisposalLocation: row.otherWasteDisposalLocation,
    whoDeliversWorkAreaOp: row.whoDeliversWorkAreaOp,
    workerExecutor: row.workerExecutor,
    workCompleted: row.workCompleted,
    cleanAndTidyWorkArea: row.cleanAndTidyWorkArea,
    additionalObservations: row.additionalObservations,
    observations: row.observations,
    acceptTerms: row.acceptTerms,
    startDate: row.startDate.toISOString(),
    endDate: row.endDate.toISOString(),
    initialAreaMeasurement: row.initialAreaMeasurement,
    approvalDate: row.approvalDate?.toISOString() ?? null,
    approvalById: row.approvalById,
    approvalByName: row.approvalBy?.name ?? null,
    approvalNotes: row.approvalNotes,
    closingDate: row.closingDate?.toISOString() ?? null,
    closingById: row.closingById,
    closingByName: row.closingBy?.name ?? null,
    preventionOfficerId: row.preventionOfficerId,
    preventionOfficerName: row.preventionOfficerUser?.name ?? null,
    otNumberId: row.otNumberId,
    otNumber: row.otNumber?.otNumber ?? null,
    userId: row.userId,
    userName: row.user.name,
    companyId: row.companyId,
    companyName: row.company.name,
    participantCount: row._count.participants,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  }
}
