import { Prisma } from "@/generated/prisma/client"

const workOrderSelect = {
  id: true,
  otNumber: true,
  type: true,
  status: true,
  progress: true,
  priority: true,
  capex: true,
  solicitationDate: true,
  solicitationTime: true,
  programDate: true,
  estimatedHours: true,
  estimatedDays: true,
  estimatedEndDate: true,
  endDate: true,
  workRequest: true,
  workDescription: true,
  isWorkBookInit: true,
  workBookName: true,
  workBookLocation: true,
  workBookStartDate: true,
  closureRequestedById: true,
  closureRequestedAt: true,
  closureApprovedById: true,
  closureApprovedAt: true,
  closureRejectedReason: true,
  maintenancePlanTaskId: true,
  workRequestId: true,
  companyId: true,
  company: { select: { name: true } },
  supervisorId: true,
  supervisor: { select: { name: true } },
  responsibleId: true,
  responsible: { select: { name: true } },
  equipments: { select: { id: true, name: true } },
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.WorkOrderSelect

export type WorkOrderRow = Prisma.WorkOrderGetPayload<{
  select: typeof workOrderSelect
}>

export { workOrderSelect }

export function flattenWorkOrder(row: WorkOrderRow) {
  return {
    id: row.id,
    otNumber: row.otNumber,
    type: row.type,
    status: row.status,
    progress: row.progress,
    priority: row.priority,
    capex: row.capex,
    solicitationDate: row.solicitationDate.toISOString(),
    solicitationTime: row.solicitationTime,
    programDate: row.programDate.toISOString(),
    estimatedHours: row.estimatedHours,
    estimatedDays: row.estimatedDays,
    estimatedEndDate: row.estimatedEndDate.toISOString(),
    endDate: row.endDate?.toISOString() ?? null,
    workRequest: row.workRequest,
    workDescription: row.workDescription,
    isWorkBookInit: row.isWorkBookInit,
    workBookName: row.workBookName,
    workBookLocation: row.workBookLocation,
    workBookStartDate: row.workBookStartDate?.toISOString() ?? null,
    closureRequestedById: row.closureRequestedById,
    closureRequestedAt: row.closureRequestedAt?.toISOString() ?? null,
    closureApprovedById: row.closureApprovedById,
    closureApprovedAt: row.closureApprovedAt?.toISOString() ?? null,
    closureRejectedReason: row.closureRejectedReason,
    maintenancePlanTaskId: row.maintenancePlanTaskId,
    workRequestId: row.workRequestId,
    companyId: row.companyId,
    companyName: row.company?.name ?? null,
    supervisorId: row.supervisorId,
    supervisorName: row.supervisor.name,
    responsibleId: row.responsibleId,
    responsibleName: row.responsible.name,
    equipmentIds: JSON.stringify(row.equipments.map((e: { id: string }) => e.id)),
    equipmentNames: JSON.stringify(row.equipments.map((e: { name: string }) => e.name)),
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  }
}
