-- CreateEnum
CREATE TYPE "WORK_PERMIT_STATUS" AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED');

-- AlterTable
ALTER TABLE "work_permit" ADD COLUMN     "endDate" TIMESTAMP(3),
ADD COLUMN     "status" "WORK_PERMIT_STATUS" NOT NULL DEFAULT 'ACTIVE';
