export const EntityTypeLabels: Record<string, string> = {
	WorkEntry: "Actividades",
	Milestone: "Hitos",
	WorkPermit: "Permisos de trabajo",
	StartupFolderDocument: "Documento Carp. de Arranque",
	VehicleDocument: "Documento Vehículo",
	BasicDocument: "Documento Básico",
	WorkerDocument: "Documento Trabajador",
	LaborControlDocument: "Documento Control Laboral",
	"Startup Folder": "Carpeta de Arranque",
	StartupFolder: "Carpeta de Arranque",
	"Work Order": "Orden de Trabajo",
	WorkOrder: "Orden de Trabajo",
	WorkRequest: "Solicitud de Trabajo",
	Equipment: "Equipo",
	User: "Usuario",
	Company: "Empresa",
	File: "Archivo",
	Folder: "Carpeta",
	SafetyTalk: "Charla de Seguridad",
	MaintenancePlan: "Plan de Mantenimiento",
	MaintenancePlanTask: "Tarea de Mantenimiento",
	LockoutPermit: "Permiso de Bloqueo",
	Notification: "Notificación",
	SupportTicket: "Ticket de Soporte",
}
