export const OTC_INTERNAL_ROLES_VALUES = {
	GENERAL_SUPERVISOR: "GENERAL_SUPERVISOR",
	AREA_SUPERVISOR: "AREA_SUPERVISOR",
	PREVENTION_OFFICER: "PREVENTION_OFFICER",
	OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
	MAINTENANCE_SUPERVISOR: "MAINTENANCE_SUPERVISOR",
	ENVIRONMENTAL_SUPERVISOR: "ENVIRONMENTAL_SUPERVISOR",
	QUALITY_SUPERVISOR: "QUALITY_SUPERVISOR",
	NONE: "NONE",
} as const

export const OTC_INTERNAL_ROLES_VALUES_ARRAY = [
	OTC_INTERNAL_ROLES_VALUES.GENERAL_SUPERVISOR,
	OTC_INTERNAL_ROLES_VALUES.AREA_SUPERVISOR,
	OTC_INTERNAL_ROLES_VALUES.PREVENTION_OFFICER,
	OTC_INTERNAL_ROLES_VALUES.OPERATIONS_MANAGER,
	OTC_INTERNAL_ROLES_VALUES.MAINTENANCE_SUPERVISOR,
	OTC_INTERNAL_ROLES_VALUES.ENVIRONMENTAL_SUPERVISOR,
	OTC_INTERNAL_ROLES_VALUES.QUALITY_SUPERVISOR,
	OTC_INTERNAL_ROLES_VALUES.NONE,
] as const

export const InternalRoleOptions = [
	{
		value: OTC_INTERNAL_ROLES_VALUES.GENERAL_SUPERVISOR,
		label: "Supervisor General",
	},
	{
		value: OTC_INTERNAL_ROLES_VALUES.AREA_SUPERVISOR,
		label: "Supervisor de Área",
	},
	{
		value: OTC_INTERNAL_ROLES_VALUES.PREVENTION_OFFICER,
		label: "Oficial de Prevención",
	},
	{
		value: OTC_INTERNAL_ROLES_VALUES.OPERATIONS_MANAGER,
		label: "Gerente de Operaciones",
	},
	{
		value: OTC_INTERNAL_ROLES_VALUES.MAINTENANCE_SUPERVISOR,
		label: "Supervisor de Mantenimiento",
	},
	{
		value: OTC_INTERNAL_ROLES_VALUES.ENVIRONMENTAL_SUPERVISOR,
		label: "Supervisor Ambiental",
	},
	{
		value: OTC_INTERNAL_ROLES_VALUES.QUALITY_SUPERVISOR,
		label: "Supervisor de Calidad",
	},
	{
		value: OTC_INTERNAL_ROLES_VALUES.NONE,
		label: "Ninguno",
	},
]
