import { ROOT_FOLDER_TYPE } from "@prisma/client"

export const ROOT_FOLDER_TYPES_ARRAYS: ROOT_FOLDER_TYPE[] = [
	ROOT_FOLDER_TYPE.COMPANY_INFORMATION,
	ROOT_FOLDER_TYPE.RISK_PREVENTION,
	ROOT_FOLDER_TYPE.WORK_PROCEDURES,
	ROOT_FOLDER_TYPE.PERSONNEL_DOCUMENTS,
	ROOT_FOLDER_TYPE.OCCUPATIONAL_EXAMS,
	ROOT_FOLDER_TYPE.INTERNAL_REGULATIONS,
	ROOT_FOLDER_TYPE.INFORMATION_DUTIES,
	ROOT_FOLDER_TYPE.PPE_DELIVERY,
	ROOT_FOLDER_TYPE.PPE_CERTIFICATES,
	ROOT_FOLDER_TYPE.VEHICLES,
	ROOT_FOLDER_TYPE.SAFETY_ADVISOR,
	ROOT_FOLDER_TYPE.LEGAL,
]

export const ROOT_FOLDERS_CLASSNAMES = {
	[ROOT_FOLDER_TYPE.COMPANY_INFORMATION]: "bg-primary/10 text-primary",
	[ROOT_FOLDER_TYPE.RISK_PREVENTION]: "bg-green-500/10 text-green-500",
	[ROOT_FOLDER_TYPE.WORK_PROCEDURES]: "bg-amber-500/10 text-amber-500",
	[ROOT_FOLDER_TYPE.PERSONNEL_DOCUMENTS]: "bg-purple-500/10 text-purple-500",
	[ROOT_FOLDER_TYPE.OCCUPATIONAL_EXAMS]: "bg-blue-500/10 text-blue-500",
	[ROOT_FOLDER_TYPE.INTERNAL_REGULATIONS]: "bg-teal-500/10 text-teal-500",
	[ROOT_FOLDER_TYPE.INFORMATION_DUTIES]: "bg-orange-500/10 text-orange-500",
	[ROOT_FOLDER_TYPE.PPE_DELIVERY]: "bg-primary/10 text-primary",
	[ROOT_FOLDER_TYPE.PPE_CERTIFICATES]: "bg-primary/10 text-primary",
	[ROOT_FOLDER_TYPE.VEHICLES]: "bg-primary/10 text-primary",
	[ROOT_FOLDER_TYPE.SAFETY_ADVISOR]: "bg-primary/10 text-primary",
	[ROOT_FOLDER_TYPE.LEGAL]: "bg-primary/10 text-primary",
}
