export const TASK_FREQUENCY_VALUES = {
	MONTHLY: "MONTHLY",
	BIMONTHLY: "BIMONTHLY",
	QUARTERLY: "QUARTERLY",
	FOURMONTHLY: "FOURMONTHLY",
	BIANNUAL: "BIANNUAL",
	YEARLY: "YEARLY",
} as const

export const TASK_FREQUENCY_VALUES_ARRAY = [
	TASK_FREQUENCY_VALUES.MONTHLY,
	TASK_FREQUENCY_VALUES.BIMONTHLY,
	TASK_FREQUENCY_VALUES.QUARTERLY,
	TASK_FREQUENCY_VALUES.FOURMONTHLY,
	TASK_FREQUENCY_VALUES.BIANNUAL,
	TASK_FREQUENCY_VALUES.YEARLY,
] as const

export const TaskFrequencyOptions = [
	{
		label: "Mensual",
		value: TASK_FREQUENCY_VALUES.MONTHLY,
	},
	{
		label: "Bimestral",
		value: TASK_FREQUENCY_VALUES.BIMONTHLY,
	},
	{
		label: "Trimestral",
		value: TASK_FREQUENCY_VALUES.FOURMONTHLY,
	},
	{
		label: "Cuatrimestral",
		value: TASK_FREQUENCY_VALUES.QUARTERLY,
	},
	{
		label: "Semestral",
		value: TASK_FREQUENCY_VALUES.BIANNUAL,
	},
	{
		label: "Anual",
		value: TASK_FREQUENCY_VALUES.YEARLY,
	},
]

export const TaskFrequencyLabels = {
	[TASK_FREQUENCY_VALUES.MONTHLY]: "Mensual",
	[TASK_FREQUENCY_VALUES.BIMONTHLY]: "Bimestral",
	[TASK_FREQUENCY_VALUES.QUARTERLY]: "Cuatrimestral",
	[TASK_FREQUENCY_VALUES.FOURMONTHLY]: "Trimestral",
	[TASK_FREQUENCY_VALUES.BIANNUAL]: "Semestral",
	[TASK_FREQUENCY_VALUES.YEARLY]: "Anual",
}
