export const WORK_ORDER_TYPE_VALUES = {
	CORRECTIVE: "CORRECTIVE",
	PREVENTIVE: "PREVENTIVE",
	PREDICTIVE: "PREDICTIVE",
} as const

export const WORK_ORDER_TYPE_VALUES_ARRAY = [
	WORK_ORDER_TYPE_VALUES.CORRECTIVE,
	WORK_ORDER_TYPE_VALUES.PREVENTIVE,
	WORK_ORDER_TYPE_VALUES.PREDICTIVE,
] as const

export const WorkOrderTypeOptions = [
	{
		value: WORK_ORDER_TYPE_VALUES.CORRECTIVE,
		label: "Correctivo",
	},
	{
		value: WORK_ORDER_TYPE_VALUES.PREVENTIVE,
		label: "Preventivo",
	},
	{
		value: WORK_ORDER_TYPE_VALUES.PREDICTIVE,
		label: "Predictivo",
	},
]
