export const WORK_ORDER_STATUS_VALUES = {
	PENDING: "PENDING",
	IN_PROGRESS: "IN_PROGRESS",
	COMPLETED: "COMPLETED",
	CANCELLED: "CANCELLED",
	EXPIRED: "EXPIRED",
	CLOSURE_REQUESTED: "CLOSURE_REQUESTED",
	CLOSED: "CLOSED",
} as const

export const WORK_ORDER_STATUS_VALUES_ARRAY = [
	WORK_ORDER_STATUS_VALUES.PENDING,
	WORK_ORDER_STATUS_VALUES.IN_PROGRESS,
	WORK_ORDER_STATUS_VALUES.COMPLETED,
	WORK_ORDER_STATUS_VALUES.CANCELLED,
	WORK_ORDER_STATUS_VALUES.EXPIRED,
	WORK_ORDER_STATUS_VALUES.CLOSURE_REQUESTED,
	WORK_ORDER_STATUS_VALUES.CLOSED,
] as const

export const WorkOrderStatusLabels = {
	PENDING: "Pendiente",
	IN_PROGRESS: "En Proceso",
	COMPLETED: "Completado",
	CANCELLED: "Cancelado",
	EXPIRED: "Expirado",
	CLOSURE_REQUESTED: "Cierre Solicitado",
	CLOSED: "Cerrado",
}

export const WorkOrderStatusOptions = [
	{
		value: WORK_ORDER_STATUS_VALUES.PENDING,
		label: "Pendiente",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.IN_PROGRESS,
		label: "En Proceso",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.COMPLETED,
		label: "Completado",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.CANCELLED,
		label: "Cancelado",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.EXPIRED,
		label: "Expirado",
	},
]
