export const WORK_ORDER_STATUS_VALUES = {
	PENDING: "PENDING",
	IN_PROGRESS: "IN_PROGRESS",
	COMPLETED: "COMPLETED",
	CANCELLED: "CANCELLED",
	EXPIRED: "EXPIRED",
} as const

export const WORK_ORDER_STATUS_VALUES_ARRAY = [
	WORK_ORDER_STATUS_VALUES.PENDING,
	WORK_ORDER_STATUS_VALUES.IN_PROGRESS,
	WORK_ORDER_STATUS_VALUES.COMPLETED,
	WORK_ORDER_STATUS_VALUES.CANCELLED,
	WORK_ORDER_STATUS_VALUES.EXPIRED,
] as const

export const WorkOrderStatusOptions = [
	{
		value: WORK_ORDER_STATUS_VALUES.PENDING,
		label: "Pendiente",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.IN_PROGRESS,
		label: "En Proceso",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.COMPLETED,
		label: "Completado",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.CANCELLED,
		label: "Cancelado",
	},
	{
		value: WORK_ORDER_STATUS_VALUES.EXPIRED,
		label: "Expirado",
	},
]
