export const WORK_PERMIT_STATUS_VALUES = {
	PENDING: "PENDING",
	IN_PROGRESS: "IN_PROGRESS",
	COMPLETED: "COMPLETED",
	CANCELLED: "CANCELLED",
	EXPIRED: "EXPIRED",
} as const

export const WORK_PERMIT_STATUS_VALUES_ARRAY = [
	WORK_PERMIT_STATUS_VALUES.PENDING,
	WORK_PERMIT_STATUS_VALUES.IN_PROGRESS,
	WORK_PERMIT_STATUS_VALUES.COMPLETED,
	WORK_PERMIT_STATUS_VALUES.CANCELLED,
	WORK_PERMIT_STATUS_VALUES.EXPIRED,
] as const

export type WorkPermitStatus = keyof typeof WORK_PERMIT_STATUS_VALUES

export const WorkPermitStatusOptions = [
	{
		value: WORK_PERMIT_STATUS_VALUES.PENDING,
		label: "Pendiente",
	},
	{
		value: WORK_PERMIT_STATUS_VALUES.IN_PROGRESS,
		label: "En Proceso",
	},
	{
		value: WORK_PERMIT_STATUS_VALUES.COMPLETED,
		label: "Completado",
	},
	{
		value: WORK_PERMIT_STATUS_VALUES.CANCELLED,
		label: "Cancelado",
	},
	{
		value: WORK_PERMIT_STATUS_VALUES.EXPIRED,
		label: "Expirado",
	},
]
